# yamllint disable rule:line-length
# yamllint disable rule:braces

name: Coding Standards

on:
  pull_request:
  push:
    branches:
      - main
      - master

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  coding-standards:
    permissions:
      contents: read

    runs-on: ubuntu-latest

    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-version: ['8.2']
        check:
          - makefile-target: 'php-cs-fixer-lint'
            name: 'PHP-CS-Fixer'
            cache: var/php-cs-fixer-cache
          - makefile-target: 'phpstan'
            name: 'PHPStan'
            cache: var/phpstan-cache
          - makefile-target: 'rector-lint'
            name: 'Rector'
            cache: var/rector-cache

    name: ${{ matrix.check.name }} on PHP ${{ matrix.php-version }}

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup PHP
        uses: shivammathur/setup-php@44454db4f0199b8b9685a5d763dc37cbf79108e1 # 2.36.0
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer:v2

      - name: Configure ${{ matrix.check.cache }} GitHub Actions cache
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          path: ${{ matrix.check.cache }}
          key: "${{ matrix.php-version }}-${{ matrix.check.makefile-target }}-${{ github.run_id }}"
          restore-keys: "${{ matrix.php-version }}-${{ matrix.check.makefile-target }}"

      - name: Install Composer dependencies
        uses: ramsey/composer-install@3cf229dc2919194e9e36783941438d17239e8520 # 3.1.1

      - name: Run ${{ matrix.check.makefile-target }}
        run: make ${{ matrix.check.makefile-target }}

  # This is a meta job to avoid to have to constantly change the protection rules
  # whenever we touch the matrix.
  tests-status:
    name: CS Status
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: coding-standards
    if: always()
    steps:
      - name: Successful run
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0

      - name: Failing run
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1
